### ISSUE TITLE
does it work with other languaje?

### ISSUE THREAD

**Issue by Drazcat** [huylenguyen806/vnasr#1]
if i change the vocabulary file, will ir work with other languaje? or this code is for vietnamese only?

**Comment by huylenguyen806** [comment]
> if i change the vocabulary file, will ir work with other languaje? or this code is for vietnamese only?

It will work with any languages having small amount of characters, like 28 in english including ' and space. Languages like korean, mandarin and japanese have too much characters (more than 10k) so they only use 2-3k common characters for asr. The larger the number of classes, the harder CTC can decode.
This code is not tested yet, so you may meet some bugs :))
